```name: Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t ${{ secrets.TREXDP}}/${{ secrets.HI}}:latest
      - name: publish
        run: |
          docker login -u ${{ secrets.TREXDP}} -p ${{ secrets.DCKR_PAR_PIPKFYDVP6TN_EV1KGF9I3JMESC}}
          docker push ${{ secrets.TREXDP}}/${{ secrets.HI}}:latest```

